# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            'Max Zimmermann'
tagline:          ''
description:      'Aspiring Researcher from Darmstadt, Germany'
url:              http://hyde.getpoole.com
baseurl:          

author:
  name:           'Mark Otto'
  url:            https://twitter.com/mdo

paginate:         100

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/zimmermax98/zimmermax98.github.io

kramdown:
  input: GFM
  hard_wrap: false
gems:
  - jekyll-coffeescript
  - jekyll-gist
  - jekyll-mentions
  - jekyll-paginate
  - jekyll-redirect-from
whitelist:
  - jekyll-coffeescript
  - jekyll-gist
  - jekyll-mentions
  - jekyll-paginate
  - jekyll-redirect-from
